// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RateResponse.proto

package com.spothero.challenge.bo;

public final class RateResponseProtoc {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RateResponse_RateResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_RateResponse_RateResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\022RateResponse.proto\022\014RateResponse\"\034\n\014Ra" +
                        "teResponse\022\014\n\004rate\030\001 \002(\005B/\n\031com.spothero" +
                        ".challenge.boB\022RateResponseProtoc"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_RateResponse_RateResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_RateResponse_RateResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_RateResponse_RateResponse_descriptor,
                new java.lang.String[]{"Rate",});
    }

    private RateResponseProtoc() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface RateResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RateResponse.RateResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 rate = 1;</code>
         */
        boolean hasRate();

        /**
         * <code>required int32 rate = 1;</code>
         */
        int getRate();
    }

    /**
     * Protobuf type {@code RateResponse.RateResponse}
     */
    public static final class RateResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:RateResponse.RateResponse)
            RateResponseOrBuilder {
        public static final int RATE_FIELD_NUMBER = 1;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<RateResponse>
                PARSER = new com.google.protobuf.AbstractParser<RateResponse>() {
            public RateResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RateResponse(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:RateResponse.RateResponse)
        private static final com.spothero.challenge.bo.RateResponseProtoc.RateResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.spothero.challenge.bo.RateResponseProtoc.RateResponse();
        }

        private int bitField0_;
        private int rate_;
        private byte memoizedIsInitialized = -1;

        // Use RateResponse.newBuilder() to construct.
        private RateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RateResponse() {
            rate_ = 0;
        }

        private RateResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            rate_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.spothero.challenge.bo.RateResponseProtoc.internal_static_RateResponse_RateResponse_descriptor;
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.spothero.challenge.bo.RateResponseProtoc.RateResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.spothero.challenge.bo.RateResponseProtoc.RateResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<RateResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.spothero.challenge.bo.RateResponseProtoc.internal_static_RateResponse_RateResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.spothero.challenge.bo.RateResponseProtoc.RateResponse.class, com.spothero.challenge.bo.RateResponseProtoc.RateResponse.Builder.class);
        }

        /**
         * <code>required int32 rate = 1;</code>
         */
        public boolean hasRate() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 rate = 1;</code>
         */
        public int getRate() {
            return rate_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasRate()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, rate_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, rate_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.spothero.challenge.bo.RateResponseProtoc.RateResponse)) {
                return super.equals(obj);
            }
            com.spothero.challenge.bo.RateResponseProtoc.RateResponse other = (com.spothero.challenge.bo.RateResponseProtoc.RateResponse) obj;

            boolean result = true;
            result = result && (hasRate() == other.hasRate());
            if (hasRate()) {
                result = result && (getRate()
                        == other.getRate());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasRate()) {
                hash = (37 * hash) + RATE_FIELD_NUMBER;
                hash = (53 * hash) + getRate();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RateResponse> getParserForType() {
            return PARSER;
        }

        public com.spothero.challenge.bo.RateResponseProtoc.RateResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code RateResponse.RateResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RateResponse.RateResponse)
                com.spothero.challenge.bo.RateResponseProtoc.RateResponseOrBuilder {
            private int bitField0_;
            private int rate_;

            // Construct using com.spothero.challenge.bo.RateResponseProtoc.RateResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.spothero.challenge.bo.RateResponseProtoc.internal_static_RateResponse_RateResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.spothero.challenge.bo.RateResponseProtoc.internal_static_RateResponse_RateResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.spothero.challenge.bo.RateResponseProtoc.RateResponse.class, com.spothero.challenge.bo.RateResponseProtoc.RateResponse.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                rate_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.spothero.challenge.bo.RateResponseProtoc.internal_static_RateResponse_RateResponse_descriptor;
            }

            public com.spothero.challenge.bo.RateResponseProtoc.RateResponse getDefaultInstanceForType() {
                return com.spothero.challenge.bo.RateResponseProtoc.RateResponse.getDefaultInstance();
            }

            public com.spothero.challenge.bo.RateResponseProtoc.RateResponse build() {
                com.spothero.challenge.bo.RateResponseProtoc.RateResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.spothero.challenge.bo.RateResponseProtoc.RateResponse buildPartial() {
                com.spothero.challenge.bo.RateResponseProtoc.RateResponse result = new com.spothero.challenge.bo.RateResponseProtoc.RateResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.rate_ = rate_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.spothero.challenge.bo.RateResponseProtoc.RateResponse) {
                    return mergeFrom((com.spothero.challenge.bo.RateResponseProtoc.RateResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.spothero.challenge.bo.RateResponseProtoc.RateResponse other) {
                if (other == com.spothero.challenge.bo.RateResponseProtoc.RateResponse.getDefaultInstance())
                    return this;
                if (other.hasRate()) {
                    setRate(other.getRate());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasRate()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.spothero.challenge.bo.RateResponseProtoc.RateResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.spothero.challenge.bo.RateResponseProtoc.RateResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required int32 rate = 1;</code>
             */
            public boolean hasRate() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 rate = 1;</code>
             */
            public int getRate() {
                return rate_;
            }

            /**
             * <code>required int32 rate = 1;</code>
             */
            public Builder setRate(int value) {
                bitField0_ |= 0x00000001;
                rate_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 rate = 1;</code>
             */
            public Builder clearRate() {
                bitField0_ = (bitField0_ & ~0x00000001);
                rate_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:RateResponse.RateResponse)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
